# Generated by Django 4.1.7 on 2023-03-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_dealers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('coordinates', models.TextField(blank=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Task',
            new_name='Dealer',
        ),
    ]
