# Generated by Django 4.1.7 on 2023-03-03 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_dealers', '0002_locations_rename_task_dealer'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='dealer',
            field=models.ManyToManyField(to='info_dealers.dealer'),
        ),
    ]
